version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "85:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../megatron-front/dist/megatron-front:/usr/share/nginx/html


  java-app:
    image: openjdk:17
    working_dir: /app
    #ports:
    #  - "8085:8080"
    volumes:
      - ./megatron-api:/app
      - ./db:/app/db
    environment:
      - spring.config.import=optional:file:./megatron-api/application.properties
    command: sh -c "java -jar megatron-api.jar"


